### ISSUE TITLE
🐛  Fix selected state bug in the closet

### ISSUE THREAD

**Issue by GV14982** [ClickPop/aww-rats-client#134]
Currently the closet has a bug where the selected state is on all the time:

![image](https://user-images.githubusercontent.com/7041175/145932543-9ca9aa31-3905-4cbf-877a-9e6f9c72f0f3.png)

The closet option should only show as selected when it is currently on the rat.

This is most likely an issue with the logic inside of `./src/components/closet/ClosetItem.tsx`, so I would start there.

**Comment by TahmidChowdhury** [comment]
Closing issue with potential fix that @GV14982 has checked. 🙌🏽
