### ISSUE TITLE
💄Fix double scrollbar in closet and add styles for Windows

### ISSUE THREAD

**Issue by GV14982** [ClickPop/aww-rats-client#136]
The closet currently has both an inner scrollbar and an outer scrollbar. The outer scrollbar can make it a little annoying when using the closet.

I also think we should add styles for the scrollbars on windows because dang are they ugly.

**Comment by TahmidChowdhury** [comment]
🐁 will try to take a crack at this

**Comment by cvasquez** [comment]
I think the real solution here is to:
- Restructure the page to use a `grid` or `flex` container that fills the height of the screen.
- Style the scrollbars using something like [React Scrollbar](https://www.npmjs.com/package/react-scrollbar).

**Comment by TahmidChowdhury** [comment]
Unassigning myself from this for now so someone else can pick it up if needed.

**Comment by GV14982** [comment]
Cleaning up issues gonna close this for now.
