### ISSUE TITLE
Create json mock file for front end development

### ISSUE THREAD

**Issue by cvasquez** [ClickPop/aww-rats-client#164]
To speed up the front end component development for the Rat Race game, we should have a `json` file that contains mock data we need.

Let's populate this as we go and find we need new mock data. This ticket is for creating the file and hooking it up to the front end.

**Comment by GV14982** [comment]
I don't really think this is needed so much now that we have Hasura setup.

**Comment by cvasquez** [comment]
We decided not to do this. Instead @GV14982 is going to create a context to use for building out the app.
