### ISSUE TITLE
Write First 5 Encounters.

### ISSUE THREAD

**Issue by cvasquez** [ClickPop/aww-rats-client#192]
Using [Rat Race Lore](https://docs.google.com/document/d/1iKIc-DPi4SWWH4ALCXAl21TacvZrRGp0z1ndH3b1NM8/edit#heading=h.2opaasr9qgii) as a guide, write first 5 encounters.

Needs to include:
- Title.
- Description.
- Weaknesses.
- Strengths.

## Notes
- All solo encounters.
- No rat type restricted slots.
- Should all be "internal" type encounters that don't move the overall story forward.

**Comment by cvasquez** [comment]
Draft thread on encounters. I'll nest each encounter as a comment below.

**Comment by GV14982** [comment]
Where are we on this? Are we missing any data here?

**Comment by GV14982** [comment]
Closing this
