### ISSUE TITLE
Create Illustrations for First 5 Encounters

### ISSUE THREAD

**Issue by cvasquez** [ClickPop/aww-rats-client#193]
Design illustrations for the first 5 encounters created in #192.

## Notes
- Design at a resolution of at least 1200x1200.
- Export at 640x640.

**Comment by GV14982** [comment]
@inessamedi Is this completed?

**Comment by inessamedi** [comment]
find your dorm, grab some munchies and decorate your dorm are completed.

**Comment by GV14982** [comment]
Closing this
