### ISSUE TITLE
Add Modal Component to Component Library

### ISSUE THREAD

**Issue by cvasquez** [ClickPop/aww-rats-client#196]
- "Outcome Modal" in [Figma prototype](https://www.figma.com/file/sv5LcogdywL7lHiTgPDeVs/Rat-Race-Game?node-id=124%3A46).
- Use [Chakra modal](https://chakra-ui.com/docs/overlay/modal) component.
- Add to [Styleguide](https://www.awwrats.com/styleguide).

**Comment by GV14982** [comment]
Should this one still be considered open as the modal hasn't been fully styled?

**Comment by GV14982** [comment]
Closing this
