### ISSUE TITLE
Add Slide-in Menu Component to Component Library

### ISSUE THREAD

**Issue by cvasquez** [ClickPop/aww-rats-client#197]
- "Rat Menu" in [Figma prototype](https://www.figma.com/file/sv5LcogdywL7lHiTgPDeVs/Rat-Race-Game?node-id=124%3A46).
- Add to [Styleguide](https://www.awwrats.com/styleguide).

**Comment by GV14982** [comment]
I know this isn't in the styleguide, but can I close this @cvasquez ?

**Comment by GV14982** [comment]
Cleaning this up, so closing some of these.
