### ISSUE TITLE
Set up frontend unit tests.

### ISSUE THREAD

**Issue by cvasquez** [ClickPop/aww-rats-client#203]
@GV14982 can you please fill out the deets on this ticket?

**Comment by GV14982** [comment]
I'm gonna be honest here, I think we should put this on the back burner... I know testing is important, but currently our dev power is pretty low and I would rather get the beta up and running then set this up. How does that sound @cvasquez ?

**Comment by GV14982** [comment]
Closing this, will need to revisit.
